---
identifier_name:
  allowed_symbols: ["_"]
  min_length: 1
  max_length: 40

file_length:
  warning: 2000
  error: 1500

function_body_length:
  warning: 100
  error: 200

disabled_rules:
  - cyclomatic_complexity
  - large_tuple
  - opening_brace
  - optional_data_string_conversion
  - statement_position
  - trailing_comma
